= Modeling exercises
:author: Peter Wilson
:date: 1992-2004


== Ambiguities

. Write three sentences that are ambiguous along the lines of
'`The chicken is ready to eat`'. Can you think of more?

. How many ways can a date be writen? Are they all in use? What other
sorts of calendrical systems are there in addition to Anno Domine style 
dates?

. Ouida is said to have said
+
--
[quote]
All rowed fast but none so fast as stroke.

The word '`stroke`' has many other meanings than in this quotation.
How many ways can you interpret '`stroke`'? Write sentences which provide
examples for each meaning.
--

. A definition of a clock from Webster's (Ninth New Collegiate 
Dictionary, 1985) is:
+
--
[quote]
A registering device with
a dial and indicator attached to a mechanism to measure or gauge
its functioning or to record its output.


How many descriptions can you
think of for a timepiece? List them.
--

. Also from Webster's is this definition of a cloverleaf:
+
--
[quote]
A road plan passing one highway over another and routing turning
traffic onto connecting roadways which branch only to the right
and lead round in a circle to enter the other highway from the 
right and thus merge traffic withut left-hand turns or direct
crossings.

Write a more general description that makes no assumption about 
which side of the road people are allowed (or required) to drive on.
--

== Simple models

. Develop a categorization system for non-fiction books. (Hint --
think how they are organized in a library).

. Develop a categorization scheme for the goods sold in your local
grocery store.

. A book is written by one or more authors and is printed by a
single publisher. A book is owned by a person. Sketch a model 
that captures these statements.

. Sketch a model of a bicycle. Assume that a bicycle consists of a frame,
a saddle, handelbars, pedals, and two wheels.

. How does your model change if you include a chain connecting the 
pedals to the rear wheel, and also if you consider that a wheel has a 
hub, spokes, a rim and a tire?


[[chap_regular]]
== Regular models

. Do the following:
.. Write an information model that describes the logical content of 
a report. Assume that a report consists of a title and one or 
more authors, together with the publication date. It may have 
an abstract and may have a table of
contents. The body of the report consists of at least two sections.
Further divisions of the report are subsections and sub-subsections.
Figures and tables may also be included within any sub-subsection, or
higher level partitions. The report may have a bibliography.

.. Write an information model that describes a book. A book is similar 
to a report with the following exceptions. A book may consist of 
two or more parts, each of which must contain two or more chapters. 
Each chapter contains at least two sections. There is always a table 
of contents and there is never an abstract, although it may have 
a preface which serves the same purpose. A book may have an index.

.. Does the above description apply to all books?

.. Create an information model that supports both reports and books. 
Include anything extra that you feel is necessary that is missing 
from the above descriptions.


. Write an information model corresponding to the following description.
+
--
An international company has a number of ongoing development projects. 
A project has a unique name and is located in a specific city. There are 
a number of suppliers to the company. The suppliers have names and may have
several branches, each in a different city. Suppliers with identical names 
do not have branches in the same city. A supplier may supply one or more 
different kinds of parts to the company. A part is identified by a catalogue 
number, and also has a short description. Projects purchase parts from 
the nearest location which stocks the part. The company keeps a record 
of the purchase orders (i.e., part, supplier, and quantity) of each project.
--

. Write an information model corresponding to the following description.
+
--
A University is organised into academic, research and administrative 
departments. Administrative staff may work in any kind of department, but 
neither academic staff nor research staff work in the administrative 
departments. Academic staff teach courses and may do research work. 
Research staff are limited to research work only. Administrative staff 
neither teach nor do research. All undergraduate and some graduate 
students attend courses. There is a fee for each course, the amount of 
which differs according to the course. Students are graded on each course 
they attend, with a grade having a value between 0 and 100. It is a 
tradition, however, of the University that no student has ever been 
graded at either 0 or 100. Some undergraduate students may be employed 
part-time to assist the administrative staff, but only if their grade 
is 75 or more. All staff get paid a salary, the amount of which depends
on their position. Graduate students do research. They may teach not more than
two courses, and are paid at a fixed rate per course. No person under the age
of 18 may be paid, and the retirement age is 65. 
--

. [[ex_fluid]] Write an information model about the delivery of items 
according to the following description.
+
--
The currency of Fluidistan is the G. This is divided into the 
smaller p and z units, where G1 = 8p and 1p = 16z. The amount 190z, 
for example, is written as G1-7-12. Linear measures in Fluidistan are 
the inch and foot, where 1 foot equals 12 inches. The weight measures 
are the pound and ounce, where 1 pound is 16 ounces.

The government of Fluidistan operate a mail delivery service for 
certain kinds of item. There are also private delivery services which 
will accept any kind of item. The following are the regulations governing 
the Fluidistan mail service.


Post Cards&#58;:: The card rate is 1p&nbsp;3z. To qualify for the card rate 
a postcard must be of a uniform thickness and no thinner than 0.007 inches. 
It must be no larger than 4.25 by 6 inches and no smaller than 3.5 by 5 inches.

Letters&#58;:: The letter rate is 1p&nbsp;13z for letters weighing one ounce 
or less. The rate increases by 1p&nbsp;6z for each additional ounce or part 
thereof. An item weighing more than 11 ounces cannot be sent at the 
letter rate. Letters less than one ounce are non-standard if the length 
is greater than 11.5 inches or the height is greater than 6.125 inches 
or the thickness is greater than 0.25 inches or the length to height 
ratio is not between 1.3 and 2.5 inclusive. Non-standard letters are 
subject to a surcharge of 10z in addition to the standard rate.

Parcels&#58;:: The parcel rate is G2-4-2 for items not exceeding two 
pounds in weight. The rate increases by by 2p&nbsp;11z for each additional 
pound or part thereof, provided the weight is not greater than ten pounds. 
Above ten pounds the rate increases by 2p&nbsp;8z for each additional pound 
or part thereof. Note: Parcels weighing less than fifteen pounds and 
whose length plus girth exceeds seven feet are chargeable at the 
fifteen pound rate.

Size Standards&#58;:: Items whose thickness is less than 0.007 inches 
are not accepted for delivery. Items less than 0.25 inches in thickness 
must be rectangular in shape and at least 3.5 inches high and at 
least 5 inches long. Items weighing more than 70 pounds are not accepted 
for delivery.

Environmental&#58;:: Neither hazardous materials nor live or dead animals
will be accepted for delivery. All items, except cards, must be enclosed 
in some wrapping. Items enclosed in environmentally sound and recycleable 
wrapping are entitled to a discount of ten percent of the applicable rate; 
if this results in a fraction of a z, the rate is rounded up to the 
nearest z.
--

. [[ex_bmd]] Create an information model for the following.
+
--
The BMD authority is responsible for recording births, marriages, divorces
and deaths. At birth the name of the child, its sex, its 
date of birth, and its parents are recorded. The spouses and the date of
the marriage are recorded. A similar record is kept for each divorce.
The divorced couple and date are recorded. Deaths are
recorded after the issuance of a death certificate. The 
date of death and the signatory of the death certificate are recorded.
The legal age for marriage is eighteen, but minors between the ages of 
sixteen
and eighteen may marry with their parents' consent. Upon request, the BMD
authority will provide information on the marital status of anybody (i.e.,
whether they are single, married, divorced, widowed or deceased). They will
also provide, to the person concerned, a listing of all their ancestors.
--


== Mathematical models

. Produce a model of the following cartesian geometry items.
+
--
A _point_ is a location in space and is defined by its location
with respect to the origin of a coordinate system. The _location_
is represented by the stem:[x], stem:[y] and stem:[z] coordinate values.

A _vector_ is a direction ad is represented in terms of three numbers
corresponding to its relative extent in the
stem:[x], stem:[y] and stem:[z] coordinate directions.

A _straight line_ can be respresented by a point on the line
and a vector denoting its direction.

A _plane_ can be represented by a point through which it passes, 
and the direction of the normal to the plane surface.

A _circle_ is a planar curve (i.e., it lies in a plane). It can be
represented by a center point, the normal to the plane in which it lies,
and a non-negative radius value.

An _ellipse_ is a planar curve. It can be
represented by a center point, the normal to the plane in which it lies,
major and minor non-negative radius values, and the direction of the major
radius.

A _parabola_ is a planar curve. It can be
represented by a vertex point, the normal to the plane in which it lies,
a non-negative focal distance, and the direction of the focus from
the vertex.
--

. Write a model that captures the following
information about a very simple bridge.
+
--
Simplistically, a bridge can be considered to be a simply supported beam, of
length stem:[l], with width stem:[b] and
depth stem:[h]. The beam is of uniform material
having density stem:[d] and modulus of elasticity stem:[E].
As well as its own weight, a bridge must support a 
uniformly distributed load stem:[L], and a
point load stem:[P] at the center of the
span. There are limits on the maximum deflection,
stem:[y], of the span under load
and also limits on the maximum stress, stem:[s], in the beam.

The moment of inertia, stem:[I], of the beam cross-section is given by

[stem%unnumbered]
++++
I = {bh^{3}}/{12}
++++

and the maximum stress at any beam cross-section is given by

[stem%unnumbered]
++++
s = {Mh}/{2I}
++++

where stem:[M] is the bending moment.

For a beam of length stem:[l] with a total
uniformly distributed load of stem:[W],
the maximum  bending moment is

[stem%unnumbered]
++++
M = {Wl}/{8}
++++

while for a point load stem:[W] at the center of the beam it is

[stem%unnumbered]
++++
M = {Wl}/{4}
++++

The maximum deflection of a uniformly loaded beam is

[stem%unnumbered]
++++
y = {5Wl^{3}}/{384EI}
++++

and for a center loaded beam is

[stem%unnumbered]
++++
y = {Wl^{3}}/{48EI}
++++

Bending moments, deflections and stresses are additive with respect to 
loading conditons. That is, the total bending moment is the sum of the
bending moments for the uniform load case and the point load case.
--


== Scope changes

. In order to respond to increasing budget deficits and voter antipathy
to increased taxes, it has been decided to combine the Car Registration
Authority (see the example model) and the BMD Authority 
(see exercise&nbsp;<<ex_bmd>> in &sect;<<chap_regular>>).
Integrate the two information models to represent
the combined Authority.

. Because of the rising unemployment rate, the government of Fluidistan
is planning to increase the number of bureaucrats it employs by 
splitting its postal service into three parts. One will be responsible 
for setting the rules and regulations, another will be responsible 
for delivering cards and letters, while the third will be responsible 
for parcel delivery.
+
--
Starting with the model resulting from exercise&nbsp;<<ex_fluid>>
in &sect;<<chap_regular>>, produce two models, 
one for the letter and card branch and the other for
the parcel branch. Try and minimise changes to the starting model 
and also try and minimise the overall amount of work to produce
(i.e., create and document) the new models.

What happens when the rules and regulations change? How would you
cater for the possibility that a third model might be required
for the regulatory branch?
--





