name: build_latex
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: yegor256/latexmk-action@0.3.0
        with:
          cmd: latexmk
          path: tex

      - uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: tex/*.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            tex/*.pdf
