name: build_latex
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: yegor256/latexmk-action@0.1.16
        with:
          cmd: latexmk
          path: tex
